spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://10.1.1.71:3306/fpshop?setUnicode=true&characterEncoding=UTF8&useSSL=false
    username: paomiantv
    password: Paomiantv1&
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.1.1.71
    port: 16379
    database: 0
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/
  session:
    store-type: redis
    timeout: 0
    redis:
      flush-mode: on-save

mybatis:
    type-aliases-package: me.j360.shiro.boot.web
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

server:
  servlet:
    context-path: /
    session:
      timeout: 120h

logging:
  config: classpath:logback-spring.xml
  path: /data/shiro/logs
  level:
    root: DEBUG
    org.springframework: INFO

shiro:
  web:
    enabled: true
  sessionManager:
    sessionIdUrlRewritingEnabled: false
